var loadedQuestion = [
  "Saya cepat menyesuaikan diri dengan situasi baru",
  "Saya amat selesa dengan pengekalan cara hidup tradisi",
  "Saya sangat menghargai kehidupan berkeluarga",
  "Saya akan melakukan segala kerja secara bersistematik",
  "Saya selesa menghormati pihak berkuasa",
  "Saya mempunyai emosi yang stabil",
  "Saya sentiasa patuh kepada peraturan walau di mana saya berada",
  "Saya amat menghargai masa",
  "Saya sanggup bekerja keras untuk kepentingan organisasi",
  "Saya selesa mematuhi peraturan-peraturan yang ditetapkan",
  "Saya seorang yang suka berjimat cermat",
  "Saya tidak suka berpakaian selekeh",
  "Saya seringkali bersifat konkrit",
  "Saya seorang yang bertanggungjawab",
  "Saya bersifat keibubapaan",
  "Saya seorang yang mementingkan keharmonian",
  "Saya seorang yang amanah",
  "Saya sentiasa bersedia untuk melakukan sesuatu kerja",
  "Saya selalunya dapat membezakan perkara yang baik dan buruk dalam kehidupan",
  "Saya berpuas hati kerana dapat menolong seseorang yang memerlukan pertolongan",
  "Saya selalu memastikan kestabilan dalam suasana pekerjaan",
  "Saya seorang yang teliti dalam membuat sesuatu pekerjaan",
  "Saya sentiasa bersifat wajar dalam membuat sebarang keputusan",
  "Saya berkebolehan untuk mengendalikan urusan yang memerlukan perincian",
  "Saya mahir menyusun atur tempat kerja",
  "Saya lebih tua dari umur sebenar saya daripada segi pemikiran",
  "Saya bersemangat mengikuti subjek yang merangsang minda",
  "Saya sentiasa membaca untuk menambah ilmu pengetahuan",
  "Saya sering bertanya guru mengenai persoalan yang mengganggu minda saya",
  "Guru merupakan orang yang sangat saya hormati",
  "Saya berminat untuk meneroka semua bidang",
  "Saya seorang yang sabar",
  "Saya suka menganalisis diri sendiri dan orang lain",
  "Saya akan berpuas hati setelah kerja disiapkan dengan sempurna",
  "Saya suka membincangkan falsafah tentang sesuatu perkara",
  "Saya sering meminta penjelasan tentang sesuatu persoalan",
  "Saya suka kepada perkara yang memerlukan aktiviti penyelidikan",
  "Saya gemar membahaskan sesuatu teori",
  "Saya mempunyai prinsip hidup yang jelas",
  "Saya cenderung untuk merekacipta sesuatu yang baru",
  "Saya berkebolehan menjalankan sesuatu tugas dengan sempurna",
  "Saya sentiasa bersifat ingin tahu yang tinggi terhadap sesuatu",
  "Saya adalah seorang yang tenang",
  "Saya berminat menyertai pertandingan yang mencabar minda",
  "Bagi saya kerja itu adalah suatu permainan",
  "Saya seorang yang sangat menyukai tugas yang mencabar",
  "Saya suka merekacipta sesuatu model",
  "Saya lebih suka meneroka idea-idea baru",
  "Saya berminat untuk menyertai aktiviti-aktiviti berbentuk ilmiah",
  "Saya akan beralih ke projek yang baru setelah menyelesaikan tugas yang lama",
  "Saya mudah mesra bila berhubung dengan orang lain",
  "Saya suka kelihatan berbeza daripada orang lain",
  "Saya suka menunjukkan keperibadian saya sebenar dalam semua keadaan",
  "Saya selalu memberi dorongan kepada orang lain untuk melakukan sesuatu pekerjaan",
  "Saya senang berinteraksi dengan orang lain",
  "Saya cenderung memilih pekerjaan dalam bidang pendidikan",
  "Saya amat sesuai melibatkan diri dalam aktiviti menolong orang lain",
  "Saya lebih suka melibatkan diri dalam pekerjaan yang ada unsur-unsur kesenian",
  "Saya berkebolehan untuk menyelami perasaan orang",
  "Saya memiliki ciri-ciri seorang pengasuh",
  "Saya percaya setiap orang mempunyai harga diri",
  "Saya lebih bermotivasi sekiranya diberi dorongan",
  "Saya tidak berminat dengan aktiviti yang melibatkan persaingan",
  "Saya mahu mendapat kepujian daripada orang lain di atas setiap kejayaan saya",
  "Keadaan perbalahan selalu mengganggu emosi saya",
  "Saya seorang pendengar yang baik",
  "Adakah anda seorang yang mudah menyayangi orang lain",
  "Sekali sekala saya mudah terasa apabila orang lain bercakap mengenai diri saya",
  "Saya tidak gemar menonton cerita yang berunsur keganasan",
  "Saya mudah rasa bersalah apabila tidak mematuhi nasihat ibu bapa",
  "Saya mudah memaafkan kesalahan orang lain",
  "Saya mudah simpati kepada seseorang walaupun ternyata dia bersalah",
  "Saya suka meniru gaya orang lain",
  "Zaman persekolahan saya begitu membosankan kerana terpaksa mengikut peraturan",
  "Saya suka berkhayal tentang masa hadapan",
  "Saya adalah dalam golongan orang yang pandai",
  "Saya isikan masa lapang dengan aktiviti luar yang menyeronokkan",
  "Saya suka bergaul dengan semua orang",
  "Saya tidak gentar dengan sebarang cabaran",
  "Saya seorang yang suka aktiviti perkhemahan",
  "Persaingan adalah baik bagi saya",
  "Saya sukakan perkara yang berbentuk amali daripada teori",
  "Saya selalu menimbulkan suasana keceriaan ketika tegang",
  "Saya selalu memberikan gerakbalas yang spontan dalam setiap tindakan",
  "Saya suka kepada sesuatu yang luar biasa dan mencabar",
  "Saya sukakan aktiviti yang berbahaya tetapi menyeronokkan",
  "Saya seorang yang kelakar",
  "Saya tidak suka pelajaran yang memerlukan pembacaan yang banyak",
  "Saya suka aktiviti kokurikulum yang lasak",
  "Saya bosan dengan kerja berstruktur",
  "Saya bosan dengan kerja-kerja yang rigid",
  "Saya bosan dengan kerja yang rutin",
  "Saya puas hati dengan kerja yang melibatkan kebebasan",
  "Saya puas hati dengan kerja yang dapat menggunakan koordinasi fizikal",
  "Saya puas hati dengan kerja yang menggunakan alatan",
  "Saya seorang performer semulajadi",
  "Saya tidak suka dikongkong",
  "Saya tidak suka pada peraturan",
  "Pekerjaan tanpa jadual sangat menarik minat saya",
  "Saya suka melakukan kerja tanpa tekanan",
];

function setData() {
  let newData = [];
  loadedQuestion.forEach((data, i) => {
    newData.push({
      question: data,
      isTrue: false,
      isShow: false,
    });
  });

  newData[0].isShow = true;
  loadedQuestion = newData;
}

setData();

export default loadedQuestion;
